version: 2.1

jobs:
  check-auth:
    docker:
      - image: buildpack-deps:jessie
    steps:
      - restore_cache:
          keys:
            - auth-cache-pim
      - checkout
      - run: mkdir -p ~/auth
      - run: ls ~/auth
      - run: sh ~/project/.circleci/check_response.sh
      - save_cache:
          key: auth-cache-pim
          paths:
            - "~/auth"

workflows:
  version: 2

  auth:
    jobs:
      - check-auth
