version: 2.1

jobs:
  check-auth:
    docker:
      - image: buildpack-deps:jessie
    steps:
      - run:
          name: Install jq
          command: |
            apt-get update && apt-get install jq
      - restore_cache:
          keys:
            - auth-cache-
      - checkout
      - run: mkdir -p ~/auth
      - run: sh ~/project/.circleci/check_response.sh
      - save_cache:
          key: auth-cache-{{ checksum "~/auth/token" }}
          paths:
            - "~/auth"
      - run: cat ~/auth/token

workflows:
  version: 2

  auth:
    jobs:
      - check-auth
