version: 2.1

jobs:
  check-auth:
    steps:
      - checkout
      - run: mkdir -p ~/auth
      - run: ls ~/auth
      - run: sh ~/project/.circleci/check_response.sh

workflows:
  version: 2

  auth:
    jobs:
      - check-auth
